{
	"data": "podAnnotations:\n    secret: value\n",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": [
			{
				"vault_address": "https://srdc-vault-staging.japaneast.cloudapp.azure.com",
				"engine_path": "velocity-develop",
				"key_name": "firstkey",
				"created_at": "2022-10-03T07:00:42Z",
				"enc": "vault:v1:tqSW7mL43Ezfk/r+/xNzYZlsza2tNoC5ptPtydAeyRCVNZY/AfD5Gu57OzA/s43ERLaYzrOlT0a+63+CY82/nV889Gxz9brNidr1vARP53i7WfB1knTs4yZhkV5QIAmVi9cjvIWUOjGJRN0omlh0W5VIKKVKpcaPgDLzBDZnHSppaqNDAp6RauSBFFDklfcghh00DPxx2jcxxQFECO4VhHPyzudQ6B+eRDWrvl9nVCI4+VBAoSXd/ZZAq7ok+PzW6p3hCfX3Dzy17i59krL/xSlZtRUkNgNmscyiPFSLxI09AQHOAySTUV1uSGmDmlsd3qpU2nYexa0hL2RsDuTrPBajxvOQZ9BQEQwZzY+1CfXq+5NeVcS0QN3JVjrJfUH2UA1Gg4S8vswpiI2nx5udea8XRl49J1ls/qdRH+hOI/NXey8VAgxgvInfjpQfEzWAyuVXqfMnNciGXQRXuYAcshDBOFAngSYpXcrFMP2Lpkw6Mpnvwc9BAAXAG02T46Vtl/MMe9abCy7ML2tqbiqSqgmUWVQ22WCoToFK7Ikx83U8kQ8Jf3XzvhGerUbuhF3znxSQwDxDovyG2GoTOk1b+vWKITkh4BOQe51xI4DEHWgiclkUM47rAJmIiEtn13mWpwyyb6Pj/yH5lU4Tea0KSy82TgX0/e5BRc8PZpr6S/Q="
			}
		],
		"age": null,
		"lastmodified": "2022-10-03T07:00:42Z",
		"mac": "ENC[AES256_GCM,data:u4y31+4d0oUOEqswCKjBD8h0g41U4hValNYlkyurotj/jj7VNUC3gPZO+dwAqaIE13+38U+cJhlCcFr9UUPH+YA14yLOC63tgnYd2vlgQW/k+eO4uhs4GpWOgZOPt8TYxf+6uMICspvvTEKlCXZ4z8nDW37xhQxQCKP8h+GsZ/M=,iv:MPBLcepPSYixeEf8NiiYaQ0tIwxrKAoeP4GqmIXRhJQ=,tag:g97f1lupZ+n2zVOOZhfxMw==,type:str]",
		"pgp": null,
		"encrypted_regex": "^(secret|)$",
		"version": "3.7.3"
	}
}